# Datasource configuration for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/webapp
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# чтобы увидеть, как SpringSecurity фильтрует каждый запрос
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

# JWT configuration
jwt.secret=YourJWTSecretKeyHere1234567890   
jwt.expirationMs=86400000               
